server:
  port: 8182 #服务端口
  servlet:
    context-path: /rocketmq-consumer

spring:
  application:
    name: rocketmq-producer #指定服务名
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: demo-consumer-group
