#选择环境 激活那个环境
spring:
  profiles:
    active: pro

---
#开发环境
server:
  port: 8080
spring:
  profiles: dev
---
#测试环境
server:
  port: 8081
spring:
  profiles: test
---
#生产环境
server:
  port: 8084
spring:
  profiles: pro